version: '3'

services:
  testsmtp:
    image: mailhog/mailhog
    command: ["-smtp-bind-addr", "0.0.0.0:25"]
    user: root
    expose:
      - 25
      - 8025
    ports:
      - 8025:8025
  db:
    image: mariadb
    volumes:
      - ifxtest-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=ifxtest
      - MYSQL_DATABASE=ifxtest
      - MYSQL_USER=ifxtest
      - MYSQL_PASSWORD=ifxtest
  ui:
    build:
      context: .
      dockerfile: Dockerfile-ui
    depends_on:
      - drf
    volumes:
      - .:/app
    ports:
      - 8080:8080
  drf:
    build:
      context: .
      dockerfile: Dockerfile-drf
    depends_on:
      - db
    volumes:
      - .:/app
    links:
      - db
      - testsmtp
    ports:
      - 8099:8000
    environment:
      - IFXTEST_IFX_APP_TOKEN=52b28b781722283740d228ce311a487227ec26a4
      - IFXTEST_USERNAME=ifxtest
      - IFXTEST_PASSWORD=ifxtest
      - IFXTEST_DATABASE=ifxtest
      - IFXTEST_HOSTNAME=db
      - IFXTEST_LOGLEVEL=DEBUG
      - IFXTEST_DEBUG=TRUE
      - IFXTEST_DJANGO_KEY=akjdkwifheilskeit8n99f0k2nvi02ld0
      - SMTP_SERVER=testsmtp
      - IFX_REMOTE_USER=veradmin

volumes:
  ifxtest-data:
