FROM node:14

EXPOSE 8080

WORKDIR /app/frontend

RUN apt-get update -y && apt-get install -y vim xvfb libxtst-dev libnss3-dev libgtk-3-dev libxss-dev libasound2-dev
RUN npm install -g @vue/cli@4.5.9 @vue/cli-service@4.5.9 eslint@7.32.0 n@7.0.0 node-gyp@7.1.2 npm@6.14.10 prettier@2.3.2

# Cypress will not install successfully with -g
RUN npm install cypress@8.2.0
RUN npm install @vue/cli-plugin-e2e-cypress@4.5.13

CMD npm run-script serve
