// URL roots
export const ROOT_URL = process.env.VUE_APP_DJANGO
export const API_ROOT = `${ROOT_URL}api/`
export const LOGIN_URL = 'obtain-auth-token/'
export const DJANGO_ADMIN_ROOT = `${ROOT_URL}djadmin/`

// URLs
export const MESSAGES = 'messages/'
export const MAILINGS = 'mailings/'
export const SEND_IFXMAILING = 'send-mailing/'
export const MOCK_ERRORS = 'mock-errors/'
export const USERS = 'users/'
export const USER_FILES = 'user-files/'
export const SKINNY_USERS = 'skinny-users/'
export const SKINNY_ACCOUNTS = 'skinny-accounts/'
export const UPDATE_NANITES = 'update-nanites/'
export const NANITES = 'nanites/'
export const CONTACT_FILES = 'contact_files/'
export const GET_CONTACT_LIST = 'contacts/'
export const CONTACTS = 'contacts/'
export const ORGANIZATIONS = 'organizations/'
export const SKINNY_ORGANIZATIONS = 'get-org-list/'
export const ORGANIZATION_NAMES = 'get-org-names/'
export const UPDATE_USER_ACCOUNTS = 'billing/update-user-accounts/'
export const ACCOUNTS = 'accounts/'
export const GROUPS = 'groups/'
export const GET_LOCATION_INFO = 'get-location-info/'
export const CONTACTABLES = 'get-contactables/'
export const SET_REQUEST_STATE = 'requests/set-request-state/'
export const UPDATE_REQUESTS = 'requests/'
export const GET_REQUEST_LIST = 'requests/get-request-list/'
export const UPDATE_ONBOARD_REQUESTS = 'onboard-requests/'
export const GET_VALID_PROCESSOR_STATES = 'requests/get-valid-processor-states/'
export const PRODUCT_USAGES = 'product-usages/'
export const CALCULATE_BILLING_MONTH = 'billing/calculate-billing-month/'
export const BILLING_RECORD_LIST = 'billing/get-billing-record-list/'
export const BILLING_RECORDS = 'billing-records/'
export const BILLING_RECORD_REVIEW_NOTIFICATION = 'billing/billing-record-review-notification/'
